### ISSUE TITLE
possible bug in diff html reports

### ISSUE THREAD

**Issue by martenson** [bgruening/galaxytools#1061]
Running [diff](https://github.com/bgruening/galaxytools/blob/master/tools/diff/diff.xml) on two files with the same content with requested html report produces the following output in the stderr.

```
sed: -e expression #1, char 78: unknown option to `s'
```

The tool does not fail. Report is empty. Maybe the report could say such.

**Comment by bgruening** [comment]
@davelopez :)

**Comment by davelopez** [comment]
I'll look into it! Thanks @martenson! :)
