### ISSUE TITLE
where can I find openduck requirements?

### ISSUE THREAD

**Issue by martenson** [bgruening/galaxytools#1101]
It defines `openforcefield ` requirement here: https://github.com/bgruening/galaxytools/blob/master/chemicaltoolbox/openduck/macros.xml#L8 but anaconda has no version of  openforcefield in channels Galaxy uses (https://anaconda.org/search?q=openforcefield)

How to resolve this?

**Comment by bgruening** [comment]
@martenson I don't think this tool is usable. I think we dropped the ball at some point. @simonbray might correct me.

**Comment by simonbray** [comment]
We did not drop the ball, I deliberately chose to focus on other projects.

Regarding the conda issue, we were using nonstandard channels. It seems that that package since got migrated to conda-forge under the name `openff-toolkit`.

Are you really interested in using this @martenson?

**Comment by martenson** [comment]
Thanks for the responses @simonbray @bgruening. We are migrating an instance and Iw as not able to recreate this tool's conda environment, so I was curious how to do that. I think we got this as a part of the chemtoolbox and are using tools other than this from the suite. Please do not spend energy on this because of us.
