### ISSUE TITLE
aragorn_out_to_gff3.py: Handle introns

### ISSUE THREAD

**Issue by sjackman** [bgruening/galaxytools#115]
Does [aragorn_out_to_gff3.py](https://github.com/bgruening/galaxytools/blob/master/tools/rna_tools/trna_prediction/aragorn_out_to_gff3.py) handle introns? It doesn't appear to after scanning the code. Feature request? Here's an example of a few tRNA with introns.

```
3   tRNA-Val              c[883351,883869]	35  	(tac)i(40,443)
5   tRNA-seC               [244644,244785]	87  	(tca)i(29,57)
7   tRNA-Arg               [615338,616255]	36  	(tcg)i(40,822)
2   tRNA-Ser               [324667,326116]	35  	(gga)i(40,1354)
1   tRNA-Val                c[84563,87002]	2383	(tac)i(34,2347)
1   tRNA-Asp              c[114384,114687]	39  	(atc)i(43,206)
4   tRNA-seC               [324290,324369]	36  	(tca)i(38,6)
5   tRNA-Ser               [345441,345776]	28  	(gct)i(33,251)
7   tRNA-Val               [405066,405293]	34  	(cac)i(35,133)
3   tRNA-Asn               [367853,369971]	2062	(att)i(32,2028)
3   tRNA-Pro               [234486,236430]	1887	(agg)i(31,1856)
1   tRNA-Ser                 [66020,66741]	32  	(gct)i(37,633)
2   tRNA-Leu                 [84137,84224]	36  	(tag)i(38,10)
3   tRNA-Arg               [168865,170209]	1285	(gcg)i(32,1253)
4   tRNA-His               [175766,176602]	776 	(gtg)i(34,742)
1   tRNA-seC                c[88201,88280]	36  	(tca)i(38,6)
```

**Comment by erasche** [comment]
@sjackman it sure doesn't! I'd never seen results like that, but I only work with small viruses. How should this be marked up in the GFF3?

**Comment by erasche** [comment]
Also, I don't suppose you could link me to a fasta sequence which would produce the data with introns, so I can test?

**Comment by sjackman** [comment]
Dang, you're fast. I'll get you some data.

**Comment by sjackman** [comment]
Here you go. Thanks! https://gist.github.com/sjackman/31cd4e17347ff1af488c

**Comment by erasche** [comment]
@sjackman (never had comments on gists, I'm assuming it emails you, but in case it doesn't...)

> would you mind sharing the command you ran this with? As of Aragorn v1.2.36 I didn't seem to be able to produce any headers with a )i( sequence in them, despite trying a number of configurations.

**Comment by sjackman** [comment]
No, I didn't get a notification from the gist. That seems like a GitHub issue/bug.

**Comment by sjackman** [comment]
Sorry, I meant to post the shell command and forget.

```sh
aragorn -gcbact -i -c -w -o aragorn.tsv sample.fa
```

**Comment by erasche** [comment]
brilliant, cheres. I'll ping you when I have a fix in place

**Comment by sjackman** [comment]
I'll mention that I've only ever seen a single intron. I have no idea whether ARAGORN could possibly output multiple introns. Thanks, Eric!

**Comment by erasche** [comment]
Good to know. Having never worked with anything other than bacteriophages, I appreciate the insight.

**Comment by erasche** [comment]
@sjackman not sure how familiar you are with the internals/maker/etc, but in the gff3 file you posted I'm having a bit of trouble rationalising a couple of the feature locations:

```
1   tRNA-Lys                  c[1533,4118]	34  	(ttt)i(39,2512)
7   tRNA-Met                c[26588,26660]	34  	(cat)
8   tRNA-Tyr                 [26850,27468]	559 	(ata)i(36,523)
```

becomes:

```
1	maker	tRNA	1534	4115	100	-	.	ID=tRNA1;Parent=gene1;Name=trnK-UUU;_AED=0.48;_eAED=0.48;_QI=12|1|1|1|0|0|2|1|19
1	maker	tRNA	26588	26660	100	-	.	ID=tRNA7;Parent=gene7;Name=trnM-CAU;_AED=0.00;_eAED=0.00;_QI=0|-1|1|1|-1|0|1|1|24
1	maker	tRNA	26850	27468	100	+	.	ID=tRNA8;Parent=gene8;Name=trnV-UAC;_AED=0.48;_eAED=0.48;_QI=0|1|1|1|0|0|2|1|25

```

In the first, the location is modified, +1 on the left hand, and -3 on the right. In the second, the location is untouched. Given that the tRNA runs the full length of the feature, and that the other intron containing tRNA has an umodified location, I can't attribute it to the presence/absence of an intron. Is this a maker bug? Are you familiar enough to say?

I was just checking my work against the "reference", when I noticed a couple of these sorts of discrepancies.

**Comment by sjackman** [comment]
Hi, Eric. Very sorry. I should have mentioned that the GFF is generated not *de novo* but by aligning known-good tRNA sequences to the reference by MAKER using Exonerate. So, the coordinates of the *de novo* ARAGORN features and the MAKER/Exonerate features may not agree exactly.

**Comment by erasche** [comment]
@sjackman no worries, not a problem. That explains the differences!

**Comment by bgruening** [comment]
Seems that I missed a lot! Thanks @erasche for fixing this.
