### ISSUE TITLE
add repeat elements to tp_find_and_replace

### ISSUE THREAD

**Issue by pvanheus** [bgruening/galaxytools#1227]
[tp_find_and_replace](https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/find_and_replace.xml) is sometimes used repeatedly in workflows like the [COVID-19: variant analysis reporting](https://github.com/galaxyproject/iwc/tree/main/workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting). This is inefficient and could be made more efficient by the use of `<repeat>` in this tool. An example of this element's use is in [tp_replace_in_line](https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/replace_text_in_line.xml).

**Comment by bgruening** [comment]
So you mean searching and replacing stuff in multiple files? But return on output?

**Comment by pvanheus** [comment]
What I mean is one input, but multiple replace operations. So e.g. input:

```
ABC DEF
99% pure Galaxy
```

replace operation one: ABC -> abc
replace operation two: 99% -> 100%

then output the results:

```
abc DEF
100% pure Galaxy
```

**Comment by bernt-matthias** [comment]
I guess with a repeat the processing would be still sequential within one job. Which is more efficient (but not necessarily faster) in the sense that the overhead of creating jobs is eliminated. 

An alternative would be to use the definitions for the replacement from a file (one line corresponding to a replaceent). And then use `split file to collection` to parallelize this. In this way you can also control granularity.
