### ISSUE TITLE
GotohScan

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxytools#138]
The GotohScan program is a search tool that finds shorter sequences
(usually genes) in large database sequences (chromosomes, genomes, ..)
by computing all semi-global alignments. Thus, the query sequence is
never truncated or split into subsequences, but always mapped to the
database over its complete length. The alignment is computed via the
Gotoh-alignment algorithm using affine gap costs.

http://www.bioinf.uni-leipzig.de/Software/GotohScan/

**Comment by bgruening** [comment]
@smithcr can we close this?
xref: https://toolshed.g2.bx.psu.edu/view/rnateam/gotohscan/6845ddcd5588
