### ISSUE TITLE
MAFFT

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxytools#139]
http://mafft.cbrc.jp/alignment/software/

MAFFT is a multiple sequence alignment program for unix-like operating systems. It offers a range of multiple alignment methods, L-INS-i (accurate; for alignment of <∼200 sequences), FFT-NS-2 (fast; for alignment of <∼30,000 sequences), etc.

This exists already -> https://toolshed.g2.bx.psu.edu/view/basfplant/mafft/e4d26cd8be10, but will need to be conformed - also needs a tool_dependencies.xml

**Comment by nsoranzo** [comment]
There's also https://bitbucket.org/crs4/orione-tools/src/HEAD/custom/mafft/

**Comment by bgruening** [comment]
@nsoranzo nice to now. It's not in the TS. Any plans? I guess the missing `tool_dependency.xml` is blocking?

**Comment by nsoranzo** [comment]
`tool_dependency.xml` was blocking indeed, now I'm not using it at the new workplace.

**Comment by bgruening** [comment]
@smithcr can we close this? https://toolshed.g2.bx.psu.edu/view/rnateam/mafft
