### ISSUE TITLE
`Split file` doesn't include header in last dataset when called on rows

### ISSUE THREAD

**Issue by hechth** [bgruening/galaxytools#1424]
The tool doesn't include the header in the last row, so the resulting dataset is only a single line - see the example dataset here: https://usegalaxy.eu/api/datasets/4838ba20a6d86765d3fbd03294f83c9e/display?to_ext=tabular

This causes the problems in the parameter sweeps tested in this history: https://usegalaxy.eu/u/hechth/h/parameter-sweep-testing-hechth-202405-1-1

https://github.com/bgruening/galaxytools/blob/7e5c9f013821c8905f2c9c452a1f00891e3a0cfd/tools/text_processing/split_file_to_collection/split_file_to_collection.xml#L131

**Comment by bgruening** [comment]
Are you planning to work on this or should I?

**Comment by hechth** [comment]
Maybe @zarghamahmad has some time to look into this?

**Comment by zargham-ahmad** [comment]
Sure, I can have a look into this
