### ISSUE TITLE
PileOMeth

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxytools#143]
Process a coordinate-sorted and indexed BAM or CRAM file containing some form of BS-seq alignments and extract per-base methylation metrics from them

https://github.com/dpryan79/PileOMeth

**Comment by AGoepfert** [comment]
Im working on this

**Comment by TorHou** [comment]
@AGoepfert Wait ... Tiffany was working on this as well. Have you started with this already?

**Comment by AGoepfert** [comment]
Yes - I am almost done with it! What is Tiffanys status?

**Comment by TorHou** [comment]
Almost done .. as far as I know. She wanted to send me an update some time ago. So I'm not completely sure on the status. 
Anyway, finish it and I will tell Tiffany to work on something else and I will merge your wrappers into the ultimate comprehensive super-wrapper.

**Comment by AGoepfert** [comment]
ok cool - thanks

**Comment by AGoepfert** [comment]
Done

**Comment by bgruening** [comment]
This is done. Wrapper can be found here: https://github.com/bgruening/galaxytools/blob/master/tools/pileometh/PileOMeth.xml
