### ISSUE TITLE
agat - should the output be GFF3?

### ISSUE THREAD

**Issue by TomHarrop** [bgruening/galaxytools#1471]
Hi, just a question. AGAT seems to output GFF3, e.g. `agat_convert_sp_gxf2gxf.pl`   produces files with the header

```
 ##gff-version 3 
```

The wrapper plain GFF, e.g.

https://github.com/bgruening/galaxytools/blob/d18fae96f65d1b748fbd21b92b75ca3181fdd8bc/tools/agat/agat.xml#L338

Workaround on Galaxy is to `Edit Dataset Atrributes` and save it as gff3.

Could we just change the wrapper to output gff3 or gff1 is really needed by this tool?

Thanks!

**Comment by bgruening** [comment]
Yes, lets change the wrapper! Can you do it? Please also bump the version number.
