### ISSUE TITLE
tp_cut fails if cut by field is selected and a delimiter is provided

### ISSUE THREAD

**Issue by mvdbeek** [bgruening/galaxytools#1480]
https://github.com/bgruening/galaxytools/blob/d9c51279c061a1da948a2582d5b502ca7573adbf/tools/text_processing/text_processing/cut.xml#L12-L20

$cut_type_options.cut_element is `-f`, but the value is only set after the `-d` option, generating a command line like

```
cut  -f -d"," '1' '/corral4/main/objects/a/b/e/dataset_abe2233e-f366-4ab2-a5cf-8203c22d6f67.dat' > '/corral4/main/jobs/059/813/59813839/outputs/dataset_9e6e44e6-c98c-4952-a709-c62252053f47.dat'
```

**Comment by bgruening** [comment]
I think its this here: https://github.com/bgruening/galaxytools/pull/1448

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/bgruening/galaxytools/pull/1448
