### ISSUE TITLE
FLASh and PEAR

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxytools#150]
PEAR - http://www.exelixis-lab.org/pear
FLASh - http://ccb.jhu.edu/software/FLASH/

preferring PEAR?

@bgruening You mentioned you started wrappers for PEAR...

**Comment by bgruening** [comment]
PEAR is done: https://github.com/galaxyproject/tools-iuc/tree/master/tools/pear
I think we can close this. Thanks for cleaning up the Trello board!
