### ISSUE TITLE
SortMeRNA wrapper not on the MTS

### ISSUE THREAD

**Issue by nsoranzo** [bgruening/galaxytools#191]
Any plan on publishing https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/sortmerna on the main Tool Shed? A user of my Galaxy server asked for it.

I can help if something is missing from the wrapper.

**Comment by bgruening** [comment]
I'm not aware of any problem with it. Indeed we are using it here in Freiburg. It can be that I only included a subset of options, but it is definitely working. If you have time, please run the tests. I'm happy to move it to the MTS.

Thanks @nsoranzo

**Comment by nsoranzo** [comment]
Testing with planemo fails because the test specify a cached database which is obviously not installed.

**Comment by bgruening** [comment]
This sounds like a good reason why I stopped testing. I think at this time it was not able to test cached databases. Imho this should be possible now.

**Comment by nsoranzo** [comment]
Maybe it would be easier to just add a small FASTA rRNA database in test-data/. This would also test the database indexing.

**Comment by nsoranzo** [comment]
Any idea how to create a small rRNA database which would still match the test query sequence?

**Comment by bgruening** [comment]
I think we can use this script and a subset of one of these databases? https://github.com/biocore/sortmerna/tree/master/rRNA_databases/scripts

**Comment by nsoranzo** [comment]
I've asked @ekopylova if she can help us with the test data, can you upload the wrapper on the Tool Shed in the mean time?

**Comment by bgruening** [comment]
It's now on MTS as well and the IUC have commit access :)
Thanks Nicola!

**Comment by ekopylova** [comment]
Hello! I've sent a small example to @nsoranzo and the test data will be available via a link to the readme page shortly. Thanks @bgruening and @nsoranzo!

**Comment by bgruening** [comment]
Wonderful! Thanks @ekopylova

**Comment by nsoranzo** [comment]
Thanks @bgruening!
