### ISSUE TITLE
 KeyError: u'package_libpng_1_6_7

### ISSUE THREAD

**Issue by mictadlo** [bgruening/galaxytools#195]
Hi, I tried to install ChemicalToolBoX with the following command:

python /galaxy/galaxy/scripts/api/install_tool_shed_repositories.py -a f21d1b0c92056ca4217af86a06319ed6 -l http://localhost:8080 --url http://toolshed.g2.bx.psu.edu/ -o bgruening --name chemicaltoolbox --tool-deps --repository-deps --panel-section-name ChemicalToolBoX

but I recieved the following error:

HTTP Error 500: Internal Server Error
{"traceback": "Traceback (most recent call last):\n  File \"/galaxy/galaxy/lib/galaxy/web/framework/decorators.py\", line 251, in decorator\n    rval = func( self, trans, *args, **kwargs)\n  File \"/galaxy/galaxy/lib/galaxy/webapps/galaxy/api/tool_shed_repositories.py\", line 246, in install_repository_revision\n    payload )\n  File \"/galaxy/galaxy/lib/tool_shed/galaxy_install/install_manager.py\", line 709, in install\n    install_options\n  File \"/galaxy/galaxy/lib/tool_shed/galaxy_install/install_manager.py\", line 801, in __initiate_and_install_repositories\n    return self.install_repositories(tsr_ids, decoded_kwd, reinstalling=False)\n  File \"/galaxy/galaxy/lib/tool_shed/galaxy_install/install_manager.py\", line 844, in install_repositories\n    reinstalling=reinstalling )\n  File \"/galaxy/galaxy/lib/tool_shed/galaxy_install/install_manager.py\", line 864, in install_tool_shed_repository\n    repo_info_tuple = repo_info_dict[ tool_shed_repository.name ]\nKeyError: u'package_libpng_1_6_7'\n", "err_m

How is it possbile to fix it?

**Comment by bgruening** [comment]
Hi @mictadlo,

which Galaxy version are you using? We saw that a few times but it is not really reproducible. You can workaround this by installing CTB in small chunks. For example installing `package_libpng_1_6_7` before you install CTB.

Thanks for trying CTB!
Bjoern

ping @gregvonkuster (maybe you have a better idea?)

**Comment by mictadlo** [comment]
hi @bgruening,
Thank you for your response. I use the following Galaxy version:
commit 7144ed8f72994473606d2943f9a4f35a6b4eb739
Merge: f6b894a 8f175ef
Author: Dannon Baker <dannon.baker@gmail.com>
Date:   Fri Jul 24 10:37:18 2015 -0400
    Merge branch 'release_15.05'

Mic

**Comment by bgruening** [comment]
This is pretty recent, can you please try to install libpng at first and rerun the CTB installation?

**Comment by bgruening** [comment]
@mictadlo this should be fixed in the latest version. I have still a few patches pending for the chemicaltoolbox, but this bug should be fixed.
Would be nice if you can confirm it.

**Comment by mictadlo** [comment]
@bgruening thank you the error has disappear.
