### ISSUE TITLE
ID mapping tools based on the UniProt Service

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxytools#199]
Based on https://github.com/jdrudolph/uniprot/blob/master/uniprot.py and http://www.uniprot.org/help/programmatic_access.

The mapping tools is requested by Anika.

**Comment by AGoepfert** [comment]
I have a look on that one

**Comment by erasche** [comment]
Oooh, yes! I had a PI asking after something like this just yesterday.

**Comment by AGoepfert** [comment]
You can find the first version here: 
https://github.com/bgruening/galaxytools/tree/master/tools/rna_tools/uniprot

**Comment by bgruening** [comment]
@erasche you can find a version in the TTS: https://testtoolshed.g2.bx.psu.edu/view/bgruening/uniprot_id_mapping/
Let me know what you think. The tests are too strict, they will break for sure as soon as they update a few ID.

**Comment by bgruening** [comment]
It's now in the TS and on FR-Galaxy. Thanks @AGoepfert!
