### ISSUE TITLE
Barrnap

### ISSUE THREAD

**Issue by AGoepfert** [bgruening/galaxytools#216]
Based on https://github.com/tseemann/barrnap

Barrnap predicts the location of ribosomal RNA genes in genomes. It supports bacteria (5S,23S,16S), archaea (5S,5.8S,23S,16S), mitochondria (12S,16S) and eukaryotes (5S,5.8S,28S,18S).

I am working on it< tool wrapper, dependencies, etc.

**Comment by bgruening** [comment]
@AGoepfert barnap is already in Galaxy.
