### ISSUE TITLE
DotKnot

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxytools#222]
DotKnot is a heuristic method for pseudoknot prediction in a given RNA sequence.

DotKnot extracts stem regions from the secondary structure probability dot plot calculated by RNAfold. Recursive H-type pseudoknots and intramolecular kissing hairpins are constructed and their presence in the sequence is verified.

http://dotknot.csse.uwa.edu.au/

**Comment by AGoepfert** [comment]
I am working on that tool

**Comment by AGoepfert** [comment]
done
