### ISSUE TITLE
BamHash

### ISSUE THREAD

**Issue by smithcr** [bgruening/galaxytools#229]
https://github.com/DecodeGenetics/BamHash
Hash BAM and FASTQ files to verify data integrity

For each pair of reads in a BAM or FASTQ file we compute a hash value composed of the readname, whether it is first or last in pair, sequence and quality value. All the hash values are summed up so the result is independent of the ordering within the files. The result can be compared to verify that the pair of FASTQ files contain the same read information as the aligned BAM file.

**Comment by AGoepfert** [comment]
I am working on that tool

**Comment by AGoepfert** [comment]
done

**Comment by bgruening** [comment]
Thanks!
