### ISSUE TITLE
SortMeRNA wrapper

### ISSUE THREAD

**Issue by bebatut** [bgruening/galaxytools#272]
Hello,

I tried SortMeRNA with ToolShed wrapper. But, it does not take into account all parameters I need (seed length for `indexdb_rna` for example). 

I developed a [new wrapper](https://github.com/ASaiM/galaxytools/tree/master/tools/sortmerna), currently available on test Tool Shed.
@bgruening Are you interesting to merge your wrapper with mine?

**Comment by bgruening** [comment]
@bebatut sure! Can you create a PR against this repo?
Moreover, we try to build an `rnateam` similar to IUC but RNA centric and I would love to invite you to this group if you are interested in RNA research.

**Comment by nsoranzo** [comment]
As a contributor to bgruening's wrapper, :+1: to merge the wrappers here!

**Comment by bebatut** [comment]
I'm working on the PR :)

@bgruening I will be pleased to join the group
