### ISSUE TITLE
reago wrapper

### ISSUE THREAD

**Issue by bebatut** [bgruening/galaxytools#277]
Hi, 

Are you interested by a wrapper for [reago](https://github.com/chengyuan/reago-1.1), an assembly tool for 16S ribosomal RNA recovery from metagenomic data?
I started the wrapper but I can integrate it in your `rna_tools` if you are interested.

**Comment by bgruening** [comment]
Didn't know about this tool. Looks interesting and like a nice addition. Please feel free to add :)

**Comment by bebatut** [comment]
I will add it :)
