### ISSUE TITLE
Installation for SortMeRNA on ubuntu

### ISSUE THREAD

**Issue by bebatut** [bgruening/galaxytools#280]
Hi, 

On ubuntu, I have an error for installation of SortMeRNA:

```
Error installing tool dependency sortmerna version 2.0: 'ascii' codec can't encode character u'\u2018' in position 29: ordinal not in range(128)
```

I made some inquiries (search for non ascii code in the files, try to install sortmerna manually, ...). But I did not find why I have this error. 
Do you have any suggestion?
Thanks

Bérénice

**Comment by nsoranzo** [comment]
You should specify the client encoding of your Galaxy DB to be UTF-8 in `config/galaxy.ini` , e.g. `postgresql://galaxy:encoded_password@localhost/galaxy?client_encoding=utf8`
