### ISSUE TITLE
sailfish issues

### ISSUE THREAD

**Issue by martenson** [bgruening/galaxytools#284]
note this tool is now on Main
https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/sailfish/sailfish/0.7.6.0

 * the picture included in toolform help is too wide (2000px) and will render badly on most displays
 * the shed.yml seems to expect to be in the iuc repository but it isn't thus the link in the MTS repo to dev repo is broken

**Comment by bgruening** [comment]
Is 600px better?

**Comment by martenson** [comment]
@bgruening way better, thanks
