### ISSUE TITLE
add kobas integration

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxytools#307]
KOBAS 2.0 is an update of KOBAS (KEGG Orthology Based Annotation System). It can identify statistically significantly enriched pathways, human diseases, and functional terms for an input set of genes using biological knowledge from well-known pathway databases, disease databases, and Gene Ontology.

http://kobas.cbi.pku.edu.cn

**Comment by blankclemens** [comment]
Can be closed. https://github.com/galaxyproject/tools-iuc/pull/1012

If I have time, I'll look at the newly released KOBAS 3.0
