### ISSUE TITLE
major output problem with extract augustus features

### ISSUE THREAD

**Issue by wrf** [bgruening/galaxytools#334]
the main loop adds the first protein or coding sequence line twice, where the first 78 letters are duplicated for every protein.
this occurs because the protein sequence is building after any line with `protein sequence = [`, which includes:
`protein_seq = line`
and then a few lines later within the same loop, still processing the same text line:
`if protein_seq:`...

this can be fixed by moving the block "`if protein_seq`" to before the "`if args.protein`" block, and likewise for the "`if coding_seq`" block.

**Comment by bgruening** [comment]
@wrf thanks for the error report. I have created a PR, but I need to fix the test-data. Maybe you can look over it.

I don't understand why this is not happening in our instance (or the test-data), but your description looks valid. Need to look at this more deeply.

Thanks again!

**Comment by abretaud** [comment]
It's fixed in https://github.com/galaxyproject/tools-iuc/pull/1503 using the patch from #335
