### ISSUE TITLE
text_processing dependencies failed to install

### ISSUE THREAD

**Issue by mictadlo** [bgruening/galaxytools#374]
Hi, `text_processing` failed to install on Galaxy 15.07, because of this error https://github.com/galaxyproject/tools-iuc/issues/880

Would anyone be able to fix it?

Thank you in advance.

Mic

**Comment by bgruening** [comment]
@mictadlo are you sure you have autotools and automake installed?

**Comment by bgruening** [comment]
This should be solved with conda dependencies.
