### ISSUE TITLE
RNAsnp

### ISSUE THREAD

**Issue by TorHou** [bgruening/galaxytools#436]
http://rth.dk/resources/rnasnp/software

This tools is needed for a workflow in a project with @mmiladi.

**Comment by zwanli** [comment]
I'm working on it

**Comment by mmiladi** [comment]
@zwanli For a simple scenario wrapper you can check this Python Notebook: https://github.com/mmiladi/RNA-SNV-wrapper

**Comment by mmiladi** [comment]
@TorHou Is this one fixed? Shall we close it?

**Comment by mmiladi** [comment]
@bgruening Pls close this issue
