### ISSUE TITLE
Salmon README misleading, does it require BioConda?

### ISSUE THREAD

**Issue by peterjc** [bgruening/galaxytools#456]
A colleague recently installed your salmon wrapper from the main Tool Shed:

https://toolshed.g2.bx.psu.edu/view/bgruening/salmon/91f3a2147127

Quoting https://github.com/bgruening/galaxytools/blob/master/tools/salmon/README.rst 

> Automated Installation
> 
> Galaxy should be able to automatically install the salmon for you.
> 

This did not happen - we don't have any salmon binary or Tool Shed package present.

Are you assuming BioConda dependency resolution is turned on? If so could you update the README to say so?

**Comment by bgruening** [comment]
Oh yes, this is true, we assume that conda is enables :(
Fixed in https://github.com/bgruening/galaxytools/commit/d00810b7dff164755582ea0880f92e6c2d32b851

**Comment by peterjc** [comment]
That README update looks perfect and should save others some confusion.

For the short term we've installed salmon 0.7.2 manually, as we're still running Galaxy 16.01 which didn't have conda turned on by default.

Thank you :+1:
