### ISSUE TITLE
segemehl needs a simple test case

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxytools#465]
- [x] conda package
- [ ] test case

The test case can be similar to the BWA/Bowtie one.

https://github.com/bgruening/galaxytools/tree/master/tools/segemehl

@jfallmann is this something for you? Or can we get Steve for this.

**Comment by jfallmann** [comment]
@bgruening Already on it, Steve is working on a new Segemehl version with specific Tests, lots of changes, so Tests for this version won't work on the new one, but I'll integrate BWA/Bowtie like tests for the included version

**Comment by jfallmann** [comment]
@bgruening I think you can close this issue for now, more tests will come with the new version if that's ok

**Comment by bgruening** [comment]
@jfallmann willst mich mal anrufen?
