### ISSUE TITLE
Prinseq bowtie2 dep in tool_dependencies.xml 

### ISSUE THREAD

**Issue by nsoranzo** [bgruening/galaxytools#48]
Presently ```prinseq/tool_dependencies.xml``` downloads and installs bowtie2 v2.1.0, which may be provided instead by devteam's ```package_bowtie2_2_1_0``` in the Tool Shed.
This just came to my eyes while looking at this file, I've not tested the possible change.

**Comment by bgruening** [comment]
I updated the readme to indicate that I'm not working on this anymore.
