### ISSUE TITLE
openms plans

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxytools#494]
* [ ] fix requirements (new openms package, fixed versions, get all missing ones in conda)
* [ ] create suite-enabled shed.yaml
* [ ] migrate to galaxyp
* [ ] more testing (currently, I was able to run a workflow with 15 steps, with collections on 12 samples, not bad! :))

@blankclemens @Stortebecker what do you think?

**Comment by blankclemens** [comment]
Good points.

Regarding the dependencies: Myrimatch seems to be unavailable from official sources, regardless if binary or source. I'm not sure if there's any need?
OMSSA seems to be [available](ftp://ftp.ncbi.nlm.nih.gov/pub/lewisg/omssa/2.1.9/), although it's from 2010. Is there any evidence that these tools might be in use?

**Comment by bgruening** [comment]
Ok, then let's remove this from the requirements and put both tools on the blacklist so we do not generate new wrappers anymore for them.

**Comment by blankclemens** [comment]
That's why I put them in https://github.com/bgruening/galaxytools/blob/master/tools/openms/SKIP_TOOLS_FILE.txt ;)

**Comment by Stortebecker** [comment]
OMSSA seems to be in use: https://www.ncbi.nlm.nih.gov/pubmed/?term=omssa

**Comment by Stortebecker** [comment]
SEQUEST even more so, but it is not compatible with PS, as it seems: https://www.ncbi.nlm.nih.gov/pubmed/?term=sequest+proteomics

**Comment by Stortebecker** [comment]
... and https://compomics.github.io/projects/peptide-shaker.html#introduction

**Comment by bgruening** [comment]
@Stortebecker I guess the question is if we need support for these in OpenMS.
PS shipps it's own binaries so we do not need to care about it much.

**Comment by Stortebecker** [comment]
You lost me. The PS node crashes when using OMSSA.
