### ISSUE TITLE
methyldackel tool dep builds a file called "bin" instead of "MethylDackel"

### ISSUE THREAD

**Issue by bwlang** [bgruening/galaxytools#540]
ls -l /mnt/galaxy/data/galaxy/tool-deps/methyldackel/0.2.1/bgruening/pileometh/f112bf3dd5ff/bin
-rwxr-xr-x 1 galaxy galaxy 1639993 Mar 11 12:58 /mnt/galaxy/data/galaxy/tool-deps/methyldackel/0.2.1/bgruening/pileometh/f112bf3dd5ff/bin

I fixed the problem by renaming the bin file, creating a bin directory and moving MethylDackel inside it.

**Comment by bgruening** [comment]
@bwlang does this help? https://github.com/bgruening/galaxytools/commit/2953c88908606f4f22b3987bc4ba29bdb4c30479

**Comment by bwlang** [comment]
sorry - nope... 
maybe this is a makefile bug?

Sorry to bug you with this...
I don't know how to make changes to tool dep scripts and test without actually uninstalling and reinstalling from the toolshed. Let me know if there is a better way.

From INSTALLATION_LOG
> 
> make install prefix=/mnt/galaxy/data/galaxy/tool-deps/methyldackel/0.2.1/bgruening/pileometh/f112bf3dd5ff/bin/
> STDERR
> install: target `/mnt/galaxy/data/galaxy/tool-deps/methyldackel/0.2.1/bgruening/pileometh/f112bf3dd5ff/bin/' is not a directory: No such file or directory

**Comment by bwlang** [comment]
tested and working in my environment - thanks!
