### ISSUE TITLE
Fix typos on Replace Text in entire line (Galaxy Version 1.1.0)

### ISSUE THREAD

**Issue by jennaj** [bgruening/galaxytools#558]
Minor, but in the next revision perhaps include the fix?

**Typo1** There is `$` instead of `&` in this help line "$ (ampersand) represents the matched find pattern." The second bullet. 

**Typo2** The word "begining" in the same help line is misspelled, should be "beginning"

```
Examples of Replace Patterns

* WORLD The word 'WORLD' will be placed whereever the find pattern was found.
* FOO-&-BAR Each time the find pattern is found, it will be surrounded with 'FOO-' at the begining and '-BAR' at the end. $ (ampersand) represents the matched find pattern.
* \1 The text which matched the first parenthesis in the Find Pattern.
```

ping @bgruening

ping @davebx Typos also on tool form for (Galaxy Version 1.0.0) - that is installed at http://usegalaxy.org. We'll want to update the tool there, and probably the rest in this group to v 1.1.0 or the version with typos fixed, if that is done soon. Otherwise, maybe just update now - typos are minor.

**Comment by bgruening** [comment]
@jennaj thanks, should be fixed now. If you like and are familiar with github, feel free to change these things directly.
Especially help texts and so on are easily fixable via the github text editor.

**Comment by jennaj** [comment]
Will do, faster that way. :)
