### ISSUE TITLE
update galaxy toolshed with latest bismark wrappers

### ISSUE THREAD

**Issue by bwlang** [bgruening/galaxytools#559]
I  see only a [version from 2015](https://toolshed.g2.bx.psu.edu/repository/browse_repositories?sort=name&operation=view_or_manage_repository&f-free-text-search=bismark&id=0df2df1072d600d7) in the toolshed.

I just patched up methylation extraction to fix [some](https://github.com/bwlang/galaxytools/commit/4d41cfbdf87968727c15a13bacbeea2d86b5a2d5) [bugs](https://github.com/bwlang/galaxytools/commit/8d939517970a4d4fc1a4a3dc11773e02bc3c1b97)

But I missed that you've improved it over time since it's not in the tool shed (or if it is I can't see it)

Could you release the updated version or advise about the best way to access your tools if you're not keeping the toolshed up to date.

Thanks!

**Comment by bgruening** [comment]
I just merged a patch for these tools a few days ago and wanted to test it more, as these tools do not have tests yet :(
If you can help testing I will push them.
Btw. you should not use the methylation extractor, this tools needs to be deprecated.
Please use methyl-dackel, also in this repo.

**Comment by bwlang** [comment]
hmm - i have a working version of methyl-dackel installed, but users asked for the extractor too...
what's wrong with the extractor?

**Comment by bgruening** [comment]
It's slow and only supports Bowtie or Bismark. I will do a release tomorrow I hope the last changes are good :(

**Comment by bgruening** [comment]
Done!

**Comment by bwlang** [comment]
👍
Thanks!
