### ISSUE TITLE
Field separator for awk wrapper

### ISSUE THREAD

**Issue by mmiladi** [bgruening/galaxytools#600]
Currently the FS and OFS variables of awk wrapper are fixed to be \t. It would be very appreciated to have custom fieldseparator. Any free HiWI @TorHou  :)?

https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/text_processing

**Comment by mmiladi** [comment]
Using something like `BEGIN {FS=" "; OFS="\t"}` would be a workaround that can be added to the help as an example hint.

**Comment by bgruening** [comment]
Milad any concrete use-case?

**Comment by mmiladi** [comment]
I have tabular looking input txt files separated by whitespace. Also sometimes one wants to generate comma or tab separated output (with OFS variable). If you think the usage is rare my second comment with BEGIN field is also very fine, just it took me a while to remember one can use BEGIN statement to reset the variables passed by `-v` option.

**Comment by TorHou** [comment]
I use OFS and FS. To me that's not a workaround but the standard solution :) You are right that we could add an example for that.
