### ISSUE TITLE
salmon wrapper incorrectly detects fastq.gz file type

### ISSUE THREAD

**Issue by bwlang** [bgruening/galaxytools#611]
I get this

```
[2017-07-25 22:52:57.029] [jLog] [info] done building index

gzip: ./single.fastq: not in gzip format
```

I dont see any error in the logic... but it seems that 
is_of_type is not reliable on my installation.
```
 #set compressed = 'no'
        #if $single_or_paired.single_or_paired_opts == 'single':
            #if $single_or_paired.input_singles.ext == 'fasta':
                #set $ext = 'fasta'
            #else:
                #if $single_or_paired.input_singles.is_of_type('fastq.gz'):
                    #set compressed = 'GZ'
                #else if $single_or_paired.input_singles.is_of_type('fastq.bz2'):
                    #set compressed = 'BZ2'
                #end if
                #set $ext = 'fastq'
            #end if
            ln -s $single_or_paired.input_singles ./single.$ext
```
The input type is of type  fastqsanger according to the library metadata
 

Input Parameter | Value | Note for rerun
-- | -- | --
File Format | fastqsanger |  
async_datasets | None |  
Specify Files for Dataset (fastqsanger) | 1 uploaded datasets |  
Genome | Human Dec. 2013 (GRCh38/hg38) (hg38) |  
File Format | fastqsanger

any ideas?

**Comment by bgruening** [comment]
@bwlang which Galaxy version is this?

**Comment by bwlang** [comment]
* release_17.05

**Comment by bwlang** [comment]
i tried reinstalling as borauyar did, but i was not able to resolve the attempt to zcat fastqsanger files...

**Comment by bwlang** [comment]
I think this was be due to the fact that my datatypes.xml does not contain the fastq.gz ... types.
Perhaps a bug in the implementation of is_of_type?  
After adding the .gz types, salmon runs fine.

**Comment by nsoranzo** [comment]
@bwlang Your 17.05 `datatypes_conf.xml` should have contained `fastq.gz`, remember to keep it in sync with the sample file (or remove it if you don't have local modifications).
