### ISSUE TITLE
salmon doesn't accept PE collections?

### ISSUE THREAD

**Issue by dpryan79** [bgruening/galaxytools#620]
One of my folks just noticed that salmon doesn't accept PE collections. If I get a chance I'll make a PR.

**Comment by bgruening** [comment]
Sorry, sailfish probably as well. Never got to he point to update them :(

**Comment by dpryan79** [comment]
Looks like this was closed by https://github.com/bgruening/galaxytools/commit/3ae8a2ded704ab0b25d4bba37bb295c301861aa3#diff-2ceb5fe80c71eb7c9aa6cd1a9ca8c052
