### ISSUE TITLE
segemehl does not support multiple input files

### ISSUE THREAD

**Issue by bjoernvoss** [bgruening/galaxytools#622]
The wrapper for segemehl allows to select multiple FastA/Q files as query input, but segemehl does not support multiple input files (also not in paired-end mode). This should be changed. Furthermore support for collections would be great to work with multiple input files.

**Comment by bgruening** [comment]
@jfallmann can you look at this or should I?

**Comment by jfallmann** [comment]
@bgruening can have a look at the wrapper, the collections will have to wait

**Comment by bgruening** [comment]
Cool, thanks @jfallmann! @bjoernvoss can you test this https://github.com/bgruening/galaxytools/pull/623
Otherwise I will merge this in a few days.

**Comment by bgruening** [comment]
fixed by #623
