### ISSUE TITLE
IntaRNA libicudata version problem

### ISSUE THREAD

**Issue by bernt-matthias** [bgruening/galaxytools#624]
When executing IntaRNA I get the following error:

```
Fatal error: Exit code 127 (Error occurred. Please check Tool Standard Error)
IntaRNA: error while loading shared libraries: libicudata.so.54: cannot open shared object file: No such file or directory
```

The problem is most likely with the version, since only the following is installed:

`... database/dependencies/_conda/envs/__intarna@2.0.0/lib/libicudata.so.56.1`

**Comment by bgruening** [comment]
If you like please try #625
