### ISSUE TITLE
salmon assumes input fastq is gzipped

### ISSUE THREAD

**Issue by borauyar** [bgruening/galaxytools#628]
Hi Bjoern, 
When I run Salmon (Galaxy tool version: 0.8.2) on a fastq file, I get this error:
> [2017-09-12 15:40:25.431] [jLog] [info] done building index
> gzip: ./single.fastq: not in gzip format

Then, we checked the command that is executed, it goes like this:
`salmon quant --index ./index --libType U --unmatedReads <(zcat ./single.fastq) ...`

So, it is trying to unzip the input file. It does the same for fastq or fastqsanger formats. 

Then, I tried providing a gzipped fastq file as input, and it worked perfectly fine. 

Is Salmon by default assuming the input files are gzipped or is it a different bug as described here in [this issue](https://github.com/bgruening/galaxytools/issues/611)?

**Comment by borauyar** [comment]
The bug persists still after updating galaxy to the latest version (17.05). Providing zipped fastq files as input solves the problem. Somehow Salmon either can't read the input type, or it is just assuming that the input is gzipped fastq file.

**Comment by borauyar** [comment]
Re-installing Salmon (the same version) after updating to Galaxy 17.05 solved the problem.

**Comment by bgruening** [comment]
Mh ... but good that it is working now.
