### ISSUE TITLE
sailfish

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxytools#63]
The sailfish wrapper is work in progress.
- loc file handling
- data manager
- check parameter
- add unit-test

Moreover it will be replaced by Salmon, some github repository.

xref: https://github.com/bgruening/galaxytools/tree/master/tools/sailfish

**Comment by smithcr** [comment]
from the trello board:
--
Would be nice to have a sailfish wrapper in Galaxy.

Start is here:
https://github.com/bgruening/galaxytools/tree/master/sailfish
--

**Comment by nsoranzo** [comment]
Can be closed?

**Comment by bgruening** [comment]
jupp
