### ISSUE TITLE
Extracting binding affinity matrix from DiffBind galaxy tool

### ISSUE THREAD

**Issue by bwassie** [bgruening/galaxytools#672]
When using DiffBind in R, we can extract the binding affinity matrix as such:
`dba.peakset(sample_count, bRetrieve=TRUE,DataType=DBA_DATA_FRAME)`

Is it possible to have a way to do this in the galaxy tool? We want to use galaxy to do all of our differential analysis but still retain the binding matrix for our own downstream analyses.

**Comment by bgruening** [comment]
@bwassie thanks for the issue. This would be possible. I think we can easily add a optional output with this matrix.

**Comment by bgruening** [comment]
This should be fixed with the newest release.
