### ISSUE TITLE
data_column selector fails to generate correct index list when the number is 10 or greater and the multiple is set to false

### ISSUE THREAD

**Issue by qiagu** [bgruening/galaxytools#753]
When multiple is false, the selector is supposed to output a single number list, for example, [2], [10]. However, when the chosen column number is 10 or greater, it outputs a digits list, like [1, 0] for 10 and [1, 8] for 18.

**Comment by bgruening** [comment]
Sounds like an integer is taken as string. Maybe you need to cast it directly to int(X)?

**Comment by qiagu** [comment]
`[int (''.join(str(i) for i in c))]` works for me. But I guess the work should be done in Galaxy.

**Comment by qiagu** [comment]
Solved. 😄
