### ISSUE TITLE
Uniprot fails at both usegalaxy.org and usegalaxy.eu

### ISSUE THREAD

**Issue by jennaj** [bgruening/galaxytools#770]
MTS: https://toolshed.g2.bx.psu.edu/view/bgruening/uniprot_rest_interface/df4c547b2533

Version: UniProt ID mapping and retrieval (Galaxy Version 0.1)

Fails in a different way on each server, but consistently, and when using example data. Maybe there is a problem with the API connection?

Test histories: 

https://usegalaxy.eu/u/jenj/h/test-history-uniprot-id-map

https://usegalaxy.org/u/jen/h/test-history-uniprot-id-map-1

Prior dependency fix at .org over a year ago (with 17.09): https://github.com/galaxyproject/galaxy/issues/3721

**Comment by bgruening** [comment]
@jennaj I fixed the tool and pushed an update. Its now working on usegalaxy.eu as far as I can tell.

**Comment by jennaj** [comment]
I'll test .org on Monday and request a tool update if a pass. Thanks!

cc @davebx

**Comment by jennaj** [comment]
Apologies for the delay on this -- it dropped off my to-do list. The tool does need an update at ORG, request ticket now exists here: https://github.com/galaxyproject/usegalaxy-playbook/issues/172

Not sure if you noticed, but both versions are still in the tool panel at EU. Might be on purpose, but just in case not, seemed worth mentioning so you can remove/hide version 0.1 (if want to!).

**Comment by bgruening** [comment]
Thanks Jen for the pointer, I have hidden the tool.
