### ISSUE TITLE
Cut tool not working in new workflows

### ISSUE THREAD

**Issue by hepcat72** [bgruening/galaxytools#852]
We've got the latest version of your cut tool (1.1.0) and when I include it in a workflow, it fails with the error:

`Parameter list requires a value, but has no legal values defined.`

despite all required values being filled in.

I have not tried old workflows with this tool incorporated, so I can only attest to new workflows with the tool.  Here are some relevant screenshots:

The tool in the workflow editor:

<img width="228" alt="cutbox" src="https://user-images.githubusercontent.com/2300532/55564914-e4951680-56c6-11e9-84ac-2ca451725d6f.png">

It's set values in the workflow editor:

<img width="267" alt="cutentries" src="https://user-images.githubusercontent.com/2300532/55564943-ee1e7e80-56c6-11e9-8b6b-b4979a0a8530.png">

Its shown values in the form when running the workflow:

<img width="1196" alt="cut original should be 2 - untouched run" src="https://user-images.githubusercontent.com/2300532/55565024-14441e80-56c7-11e9-91ff-025eec602085.png">

The info on a failed output:

<img width="885" alt="cuterr" src="https://user-images.githubusercontent.com/2300532/55565070-2625c180-56c7-11e9-89a7-37f518aead3d.png">

Further, I went to view the tool in the admin settings and I get the following error:

`Error displaying tool, probably due to a problem in the tool config. The exception is: list indices must be integers, not str.`

This started happening after upgrading to 19.01.

I created a test workflow with the 2 cut tools we have.  The other succeeds:

https://galaxy.princeton.edu/u/rleach/w/cut-test

**Comment by mvdbeek** [comment]
This is more of a Galaxy issue it seems, can you transfer that issue there ?

**Comment by hepcat72** [comment]
Copied to galaxy's github page.
