### ISSUE TITLE
restructure repository

### ISSUE THREAD

**Issue by bgruening** [bgruening/galaxytools#91]
`galaxytools` should be restructured to look and feel like the tools-iuc and tools-devteam repository.

To reflect the different areas of tools and to keep the links stable I will have different `tools` directories.  

 * rna-tools
 * chemicaltoolbox

Remove useless script from the root and improve the readme file.

**Comment by bgruening** [comment]
I decided to put everything under tools, besides chemicaltoolbox. I need to preserve this link a little bit longer and this is really a special thing.

Any other comments or ideas?

**Comment by erasche** [comment]
add a .shed.yml and I'll add a jenkins job for it (if you'd like)

**Comment by bgruening** [comment]
Awesome! You need a .shed.yml file for every tool correct? This can take a little bit, I'm not sure which tools are located under which account ;)

**Comment by erasche** [comment]
Ah...yes. :/ Anything you want tested that is. That's just the easiest way to determine what is and isn't testable (rather than using a hardcoded `tools/` path)

**Comment by bgruening** [comment]
Totally agree. Thanks a bunch, but I need to figure out which tool I put under bgruening, IUC and so on. I will get back to you! :)

**Comment by erasche** [comment]
Okay, sounds great!

**Comment by bgruening** [comment]
We have added a lot of `.shed.yml` files and will do in the next weeks. @erxleben is working on this. I think the repository is in a pretty good shape now and improving, will close this now. Thanks @erasche
