### ISSUE TITLE
Alevin wrapper fails with built-in indices

### ISSUE THREAD

**Issue by pinin4fjords** [bgruening/galaxytools#921]
Running Alevin with the wrapper (0.14.1.2, Galaxy version 19.05) using defaults and a built-in index produces the error:

```
cannot find 's_index' while searching for 'refTranscriptSource.s_index.kmer'
```
The conditional in the command section seems to be failing:

```
    <command detect_errors="exit_code"><![CDATA[
        mkdir ./index
        && mkdir ./output
        #if '${refTranscriptSource.TranscriptSource}' != "indexed":
            && salmon index -i ./index
                --kmerLen '${refTranscriptSource.s_index.kmer}'
                --gencode
                --transcripts '${refTranscriptSource.s_index.fasta}'
            #set $index_path = './index'
        #else
            #set $index_path = $refTranscriptSource.index.fields.path
        #end if
...
```

i.e. even though "${refTranscriptSource.TranscriptSource}" from the macro IS (or should be) equal to 'indexed', it's still looking for the s_index.kmer value, implying it's trying to re-index. My Galaxy foo is too poor to work out why. Any ideas?

Jon

**Comment by astrovsky01** [comment]
Hi @pinin4fjords! Are you running alevin on .eu, or on a local instance? When I test both locally or on usegalaxy.eu, I don't get the error.

**Comment by pcm32** [comment]
We are testing in on a local instance, installing Alevin from the toolshed. Did you try using an built index instead of the option where the index is built?

When do you think that we can see the newest version of the wrapper pushed to the toolshed with the fix in #923? Thanks!

**Comment by astrovsky01** [comment]
@pcm32 as far as I am aware, you should be able to pull it by tomorrow morning.

**Comment by pcm32** [comment]
Thanks, it took only a few minutes to be in the toolshed, so great! I have installed it now, someone will try it tomorrow in our instance.
