### ISSUE TITLE
Setting non-default memory for paralyzer causes apparent tool failure

### ISSUE THREAD

**Issue by hepcat72** [bgruening/galaxytools#926]
If you up the galaxy memory for the PARalyzer tool wrapper, the results datasets are all red even though there's no error.  I believe this is because STDERR gets a message:

```
Picked up _JAVA_OPTIONS: -Xms5G -Xmx50G
```

and likely stringent error detection was enabled.

If you run it without any custom memory settings, nothing gets printed on STDERR and the results datasets are green.

**Comment by bgruening** [comment]
@hepcat72 please have a look at: https://github.com/bgruening/galaxytools/issues/926
