### ISSUE TITLE
data type not found and problem in running rdock

### ISSUE THREAD

**Issue by vmevada102** [bgruening/galaxytools#973]
I have Galaxy 19.01 for more than 1 year.

As an importance of the rdock tool in our galaxy, I have installed ChemicalToolBox. Unfortunately. as I am trying to run the cavity finding using rDock cavity definition tool. I am receiving two errors.

1. rdock_As datatype available
2. The rDock program is licensed under GNU-LGPLv3.0. http://rdock.sourceforge.net/
Executable:	rbcavity ($Id: //depot/dev/client3/rdock/2013.1/src/exe/rbcavity.cxx#3 $)
Library:	libRbt.so/2013.1/901 2013/11/27

kindly help me to resolve these two errors, which allow us to support COVID19.

**Comment by bgruening** [comment]
@vmevada102 welcome!

For 1) simply add https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/datatypes_conf.xml.sample#L578 into your datatypes_conf.xml file.

The 2) does not seems to be an error, this is the normal output afaik. 1) should also just be a warning. So I'm wonder what is the real error here? Can you please test your settings under https://usegalaxy.eu and see if this works?

**Comment by vmevada102** [comment]
Resolved both the error mentioned. 


Thank you @bgruening

**Comment by bgruening** [comment]
@vmevada102 is this now working? Can we close this issue?

**Comment by vmevada102** [comment]
One more issue i am facing. 
We have 19.01 version of the Galaxy.

When I am trying to import and run the workflow made by you, the following error found.

Step 5: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat/0.1.0
The tool is not installed

this tool might 1.0.0 version and the workflow has 0.1.0 version. Kidly help me to resolve the issue.

**Comment by bgruening** [comment]
@vmevada102 you need to install this tool as well: https://toolshed.g2.bx.psu.edu/view/bgruening/text_processing

**Comment by vmevada102** [comment]
Thank you for your reply, 

Unfortunately, i am not able to find via Admin>Install New Tool option> search/browse.
So, a little bit confused to get it working.

Anyways, you can close this post, as a resolution of the title of this post.

**Comment by vmevada102** [comment]
THank you @bgruening

**Comment by bgruening** [comment]
Let me know if I can help you in any way.
